"""
Day 7 — Build a static, single-file GitHub Pages demo from Day 6's results.

Reads day6_evaluation/results/comparison_per_day.csv and comparison_summary.csv,
embeds them as JSON into docs/index.html (Chart.js via CDN, no build step), so
`git push` with GitHub Pages pointed at /docs (or the gh-pages branch) serves
it directly.

Run this after run_all.py (which produces the Day 6 CSVs it reads).
"""
from __future__ import annotations
import json
import os
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DAY6 = os.path.join(ROOT, "day6_evaluation", "results")
DOCS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "docs")

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Wasserstein-GP Forecasting of Risk-Neutral Densities — Demo</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.4/chart.umd.min.js"></script>
<style>
  :root {
    --bg: #0f1115; --panel: #171a21; --border: #262a35;
    --text: #e8e9ed; --muted: #9aa0ac;
    --gp: #5b9bd5; --baseline: #d5825b; --persistence: #8a8f99;
  }
  * { box-sizing: border-box; }
  body {
    margin: 0; padding: 2.5rem 1.5rem; background: var(--bg); color: var(--text);
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  }
  .wrap { max-width: 980px; margin: 0 auto; }
  h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
  .subtitle { color: var(--muted); margin-top: 0; margin-bottom: 2rem; font-size: 0.95rem; }
  .card {
    background: var(--panel); border: 1px solid var(--border); border-radius: 10px;
    padding: 1.25rem 1.5rem; margin-bottom: 1.5rem;
  }
  .card h2 { font-size: 1.05rem; margin-top: 0; margin-bottom: 0.75rem; }
  table { width: 100%; border-collapse: collapse; font-size: 0.9rem; }
  th, td { text-align: right; padding: 0.4rem 0.6rem; border-bottom: 1px solid var(--border); }
  th:first-child, td:first-child { text-align: left; }
  th { color: var(--muted); font-weight: 500; }
  .gp-label { color: var(--gp); font-weight: 600; }
  .baseline-label { color: var(--baseline); font-weight: 600; }
  .persistence-label { color: var(--persistence); font-weight: 600; }
  .note { color: var(--muted); font-size: 0.85rem; margin-top: 0.75rem; margin-bottom: 0; }
  canvas { max-width: 100%; }
  footer { color: var(--muted); font-size: 0.8rem; margin-top: 2rem; }
  a { color: var(--gp); }
</style>
</head>
<body>
<div class="wrap">
  <h1>Wasserstein-GP Forecasting of Risk-Neutral Densities</h1>
  <p class="subtitle">
    Distribution-input Gaussian process regression on option-implied risk-neutral densities,
    vs. a moment-based linear baseline and a persistence (random-walk) benchmark.
    Milind Sahu (IISER Tirupati) &middot; Supervisor: Dr. Sven Karbach (University of Amsterdam).
  </p>

  <div class="card">
    <h2>Held-out metrics: <span class="gp-label">Wasserstein-GP</span> vs <span class="baseline-label">linear baseline</span> vs <span class="persistence-label">persistence</span></h2>
    <table id="summary-table"></table>
    <p class="note">Persistence forecasts tomorrow = today, unchanged. It's the random-walk
      null every model here has to beat before its result means anything.</p>
  </div>

  <div class="card">
    <h2>Next-day implied variance: forecast vs realized</h2>
    <canvas id="varianceChart" height="110"></canvas>
  </div>

  <div class="card">
    <h2>Wasserstein-2 forecast error (full density), by day</h2>
    <canvas id="w2Chart" height="110"></canvas>
    <p class="note">Also shown: a Gaussian fit to <em>today's own</em> realized mean/variance,
      scored against tomorrow — zero forecast skill, isolating the cost of assuming a
      Gaussian shape from any actual forecasting.</p>
  </div>

  <footer>
    Generated by day7_writeup/build_demo.py from Day 6 evaluation output.
    Source: <a href="https://github.com/itsmilindsahu" target="_blank">github.com/itsmilindsahu</a>
  </footer>
</div>

<script>
const perDay = __PER_DAY_JSON__;
const summary = __SUMMARY_JSON__;

// ---- summary table ----
const rows = [
  ["RMSE (variance target)", summary.gp_rmse, summary.baseline_rmse, summary.persistence_rmse, 3],
  ["95% coverage", summary.gp_coverage_95, summary.baseline_coverage_95, summary.persistence_coverage_95, 3],
  ["NLPD (mean, lower = better)", summary.gp_nlpd_mean, summary.baseline_nlpd_mean, summary.persistence_nlpd_mean, 3],
  ["W2 forecast error (mean)", summary.gp_w2_forecast_error_mean, summary.baseline_w2_forecast_error_mean, summary.persistence_w2_forecast_error_mean, 3],
  ["Shape-only W2 (mean removed)", summary.gp_w2_shape_only_mean, summary.baseline_w2_shape_only_mean, summary.persistence_w2_shape_only_mean, 3],
];
const table = document.getElementById("summary-table");
table.innerHTML = "<tr><th>Metric</th><th>Wasserstein-GP</th><th>Baseline</th><th>Persistence</th></tr>" +
  rows.map(r => `<tr><td>${r[0]}</td><td>${r[1].toFixed(r[4])}</td><td>${r[2].toFixed(r[4])}</td><td>${r[3].toFixed(r[4])}</td></tr>`).join("") +
  `<tr><td>Gaussian fit to today (no forecast), W2 vs. tomorrow</td><td colspan="3">${summary.noforecast_gaussian_w2_mean.toFixed(3)}</td></tr>`;

// ---- variance forecast chart ----
const labels = perDay.map(d => d.date);
new Chart(document.getElementById("varianceChart"), {
  type: "line",
  data: {
    labels,
    datasets: [
      { label: "Realized", data: perDay.map(d => d.y_true_var), borderColor: "#e8e9ed", backgroundColor: "transparent", tension: 0.2 },
      { label: "Wasserstein-GP", data: perDay.map(d => d.gp_mean), borderColor: "#5b9bd5", backgroundColor: "transparent", borderDash: [4,3], tension: 0.2 },
      { label: "Linear baseline", data: perDay.map(d => d.baseline_mean), borderColor: "#d5825b", backgroundColor: "transparent", borderDash: [4,3], tension: 0.2 },
      { label: "Persistence", data: perDay.map(d => d.persistence_mean), borderColor: "#8a8f99", backgroundColor: "transparent", borderDash: [2,2], tension: 0.2 },
    ]
  },
  options: {
    plugins: { legend: { labels: { color: "#e8e9ed" } } },
    scales: {
      x: { ticks: { color: "#9aa0ac" }, grid: { color: "#262a35" } },
      y: { ticks: { color: "#9aa0ac" }, grid: { color: "#262a35" } },
    }
  }
});

// ---- W2 error chart ----
new Chart(document.getElementById("w2Chart"), {
  type: "bar",
  data: {
    labels,
    datasets: [
      { label: "Wasserstein-GP", data: perDay.map(d => d.gp_w2_error), backgroundColor: "#5b9bd5" },
      { label: "Linear baseline", data: perDay.map(d => d.baseline_w2_error), backgroundColor: "#d5825b" },
      { label: "Persistence", data: perDay.map(d => d.persistence_w2_error), backgroundColor: "#8a8f99" },
      { label: "No-forecast Gaussian", data: perDay.map(d => d.noforecast_gaussian_w2_error), type: "line", borderColor: "#e8e9ed", backgroundColor: "transparent", borderDash: [4,3], pointRadius: 0 },
    ]
  },
  options: {
    plugins: { legend: { labels: { color: "#e8e9ed" } } },
    scales: {
      x: { ticks: { color: "#9aa0ac" }, grid: { color: "#262a35" } },
      y: { ticks: { color: "#9aa0ac" }, grid: { color: "#262a35" } },
    }
  }
});
</script>
</body>
</html>
"""


def build():
    per_day = pd.read_csv(os.path.join(DAY6, "comparison_per_day.csv"))
    summary_series = pd.read_csv(os.path.join(DAY6, "comparison_summary.csv"), index_col=0).iloc[:, 0]

    per_day_json = json.dumps(per_day.to_dict(orient="records"))
    summary_json = json.dumps(summary_series.to_dict())

    html = HTML_TEMPLATE.replace("__PER_DAY_JSON__", per_day_json).replace("__SUMMARY_JSON__", summary_json)

    os.makedirs(DOCS, exist_ok=True)
    out_path = os.path.join(DOCS, "index.html")
    with open(out_path, "w") as f:
        f.write(html)
    print(f"Wrote {out_path}")
    print("Enable GitHub Pages on this repo pointing at /docs (or push docs/ contents to gh-pages) to serve it.")


if __name__ == "__main__":
    build()
